spring.application.name=PaoloFrattarola

spring.datasource.url=jdbc:mysql://localhost/pf
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
